"""google

Revision ID: 006f297e6d96
Revises: 033ad6c9e1d1
Create Date: 2023-05-23 22:00:49.744718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006f297e6d96'
down_revision = '033ad6c9e1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
