"""Ввод гугл

Revision ID: 033ad6c9e1d1
Revises: 1f2f89f2ed01
Create Date: 2023-05-23 13:27:25.573619

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '033ad6c9e1d1'
down_revision = '1f2f89f2ed01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
