"""two migration

Revision ID: 1f2f89f2ed01
Revises: 14da128c4a98
Create Date: 2023-05-07 18:37:12.399056

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '1f2f89f2ed01'
down_revision = '14da128c4a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
