"""three migration

Revision ID: 3635fc4c6152
Revises: 14da128c4a98
Create Date: 2023-05-25 11:48:32.682370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3635fc4c6152'
down_revision = '14da128c4a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
