"""fry migration

Revision ID: 5e858004eb97
Revises: 6e076ad34b45
Create Date: 2023-05-24 16:00:14.906219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e858004eb97'
down_revision = '6e076ad34b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
