"""table

Revision ID: 6e076ad34b45
Revises: 006f297e6d96
Create Date: 2023-05-24 10:53:41.254627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e076ad34b45'
down_revision = '006f297e6d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
