"""three migration

Revision ID: f1e1db1fbfd2
Revises: 3635fc4c6152
Create Date: 2023-05-25 11:54:49.742276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e1db1fbfd2'
down_revision = '3635fc4c6152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
